### PR TITLE
implement clojure native driver for babelfish

### PR DESCRIPTION
**Pull request by erizocosmico**

### CODE REVIEW

**Comment by erizocosmico** [comment]
@smola in the end are we using JSON or msgpack?

@mcuadros could we give permissions to members so we can, at least, assign reviewers to PRs?

**Comment by erizocosmico** [comment]
@smola should I adapt this to the format used by `sdk bootstrap` now or is that still subject to change?

**Comment by erizocosmico** [comment]
Updated so it includes positional info (line, col, ...)

**Comment by erizocosmico** [comment]
can be reviewed now @smola @mcuadros 

we'd need this merged before releasing the clojure ast blgo post, as it mentions the source code of this repository

**Review by smola — APPROVED** [review]

**Comment by smola** [comment]
@erizocosmico It's subject to change, but `sdk bootstrap` should handle update of managed files. Feel free to adapt after we merge this PR.

**Comment by erizocosmico** [comment]
@smola :+1:

**Pull request merged**
