### PR TITLE
native: expand defn and treat some other forms as invoke

### PR DESCRIPTION
**Pull request by erizocosmico**
### What's changed?

* All forms with `*` suffix are macros, and thus, we are not parsing them because we are not expanding macros. So I removed them and substituted the ones where it was possible with our own implementation of the expansion so we don't lose the information the analyzer library provides for those forms.
* Fix meta being analyzed as well and resulting in a big chunk of unnecessary information.

### Why expand `defn` if technically it is a macro?

Because in not doing so, we lose information. By expanding `defn` we obtain something like this:

```clojure
(def func-name (fn [arg1 arg2] expr))
```

This falls into the category of losing information by desugaring some syntactic sugar. But I think, in the end, it's worth it. This way we don't lose the documentation of the function, we know its arity, we know the bodies of it (a function can have many), etc. Otherwise, what we'd have is an invocation of `defn` with a chunk of arguments that we'd have to parse if we want to know what is being defined.

Probably there are more cases where we want to expand macros because by not doing so we'd be losing information. We can see on the future if it's worth it or not.

### CODE REVIEW

**Review by Serabe — APPROVED** [review]

**Comment by smola** [comment]
@erizocosmico This requires rebase.

**Comment by erizocosmico** [comment]
Done (with merge, tho) @smola

**Comment by bzz** [comment]
Hmm, CI fails with

```
[0K$ go get -v -t ./...
github.com/bblfsh/sdk (download)
package github.com/bblfsh/sdk/protocol/cmd: cannot find package "github.com/bblfsh/sdk/protocol/cmd" in any of:
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/github.com/bblfsh/sdk/protocol/cmd (from $GOROOT)
	/home/travis/gopath/src/github.com/bblfsh/sdk/protocol/cmd (from $GOPATH)
github.com/stretchr/testify (download)

travis_time:end:0358dfa0:start=1493211014159837140,finish=1493211015485921247,duration=1326084107
[0K
[31;1mThe command "go get -v -t ./..." failed and exited with 1 during .[0m
```

Is that expected to fail? Or shall it be closed/re-open to trigger Travis again?

**Comment by erizocosmico** [comment]
Dockerfiles for testing and such are not done, so yes.

**Pull request merged**
